
POSSIBLE_X_COLUMNS = ['x', 'east', 'este', 'midx', 'xm', 'centroid_x', 'xcenter']
POSSIBLE_Y_COLUMNS = ['y', 'north', 'norte', 'midy', 'ym', 'centroid_x', 'xcenter']
POSSIBLE_Z_COLUMNS = ['z', 'elev', 'cota', 'midz', 'zm', 'centroid_x', 'xcenter', 'RL']
POSSIBLE_HOLEID_COLUMNS = ['dhid', 'hole', 'codigo']
POSSIBLE_FROM_COLUMNS = ['from', 'desde', 'head']
POSSIBLE_TO_COLUMNS = ['to', 'hasta', 'tail', 'depth']
POSSIBLE_LENGTH_COLUMNS = ['length', 'largo', 'avance', 'depth']
POSSIBLE_AZIM_COLUMNS = ['az', 'rumbo']
POSSIBLE_DIP_COLUMNS = ['dip', 'incli', 'manteo']
